In [1]:
import numpy as np 
def calc_sorted_eigen(A):
    eigen_val, eigen_vec = np.linalg.eig(A)
    idx = eigen_val.argsort()[::-1]   
    eigen_val = eigen_val[idx]
    eigen_vec = eigen_vec[:,idx] 
    return eigen_val, eigen_vec

In [2]:
import sys

In [4]:
# Calculate the covariance matrix and correlation "by hand"
from sklearn.preprocessing import StandardScaler

x = np.array([
    [0, 2, 4],
    [1, 1, 4],
    [2, 0, 4],
    [33, 2, 4],
    [34, 0, 4],
    [-3, 3, 3]
])
x_cent = np.mean(x, axis=0, keepdims=True)
my_cov = ((x - x_cent).T @ (x - x_cent)) / (len(x)-1)
print(f"my_cov:\n {my_cov}")

numpy_cov = np.cov(x.T)
print(f"numpy_cov:\n {numpy_cov}")

x_std_mean = StandardScaler(with_std=False).fit_transform(x)
mean_only_scaler_cov = np.cov(x_std_mean.T)
print(f"StandardScaler cov only mean:\n {mean_only_scaler_cov}")

x_std = StandardScaler().fit_transform(x)
std_scaler_cov = np.cov(x_std.T)
print(f"StandardScaler cov:\n {std_scaler_cov}")

# Calculate the normalized covariance (or correlation matrix) "by hand"
def calc_corr(cov):
    corr_coef = cov.copy()
    var = np.diag(cov)
    stddev = np.sqrt(var.real)
    corr_coef /= stddev[:, None]
    corr_coef /= stddev[None, :]
    return corr_coef

print(f"my_corr_coef:\n {calc_corr(my_cov)}")

numpy_corr_coef = np.corrcoef(x.T)
print(f"numpy_corr_coef:\n {numpy_corr_coef}")

no_mean_std_scaler_corr_coef = calc_corr(mean_only_scaler_cov)
print(f"StandardScaler cov only mean corr_coef:\n {no_mean_std_scaler_corr_coef}")

std_scaler_corr_coeff = calc_corr(std_scaler_cov)
print(f"StandardScaler cov corr_coef:\n {std_scaler_corr_coeff}")



my_cov:
 [[  3.02166667e+02  -6.26666667e+00   2.83333333e+00]
 [ -6.26666667e+00   1.46666667e+00  -3.33333333e-01]
 [  2.83333333e+00  -3.33333333e-01   1.66666667e-01]]
numpy_cov:
 [[  3.02166667e+02  -6.26666667e+00   2.83333333e+00]
 [ -6.26666667e+00   1.46666667e+00  -3.33333333e-01]
 [  2.83333333e+00  -3.33333333e-01   1.66666667e-01]]
StandardScaler cov only mean:
 [[  3.02166667e+02  -6.26666667e+00   2.83333333e+00]
 [ -6.26666667e+00   1.46666667e+00  -3.33333333e-01]
 [  2.83333333e+00  -3.33333333e-01   1.66666667e-01]]
StandardScaler cov:
 [[ 1.2        -0.35721431  0.47910562]
 [-0.35721431  1.2        -0.80903983]
 [ 0.47910562 -0.80903983  1.2       ]]
my_corr_coef:
 [[ 1.         -0.29767859  0.39925468]
 [-0.29767859  1.         -0.67419986]
 [ 0.39925468 -0.67419986  1.        ]]
numpy_corr_coef:
 [[ 1.         -0.29767859  0.39925468]
 [-0.29767859  1.         -0.67419986]
 [ 0.39925468 -0.67419986  1.        ]]
StandardScaler cov only mean corr_coef:
 [[ 1.     

/Users/kevinlu/miniconda3/envs/pytorch/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [6]:
# Calculate the eigenvectors and eigenvalues by hand

A = np.array([
    [3, 0, 1],
    [-4, 1, 2], 
    [-6, 0, -2]
])

b1 = np.array([2, 2, 1]).reshape(-1, 1)
b2 = np.array([-1, 0, 2]).reshape(-1, 1)
b3 = np.array([0, 1, 0]).reshape(-1, 1)
b4 = np.array([0, -1, 0]).reshape(-1, 1)
b5 = np.array([3, 2, 1]).reshape(-1, 1)
b6 = np.array([-0.09534626, -0.95346259,  0.28603878]).reshape(-1, 1)

for i, b in enumerate([b1, b2, b3, b4, b5, b6], 1):
    print(f"b{i}")
    print(A @ b)

eigen_val, eigen_vec = calc_sorted_eigen(A)
print(f"Eigen vec:\n{eigen_vec}")
print(f"Eigen vec_t:\n{eigen_vec.T}")
for val, vec in zip(eigen_val, eigen_vec.T): # note here that np.linalg.eigen gives the transpose of the eigenvectors
    print(f"Eigenvalue: {val}")
    print(f"Eigenvector: {vec}")
# We see that [0, 1, 0] is an eigen vector with an eigen value of 1

b1
[[  7]
 [ -4]
 [-14]]
b2
[[-1]
 [ 8]
 [ 2]]
b3
[[0]
 [1]
 [0]]
b4
[[ 0]
 [-1]
 [ 0]]
b5
[[ 10]
 [ -8]
 [-20]]
b6
[[  0.00000000e+00]
 [  1.00000001e-08]
 [  0.00000000e+00]]
Eigen vec:
[[  5.55111512e-17   0.00000000e+00  -9.53462589e-02]
 [ -1.00000000e+00   1.00000000e+00  -9.53462589e-01]
 [ -1.11022302e-16   0.00000000e+00   2.86038777e-01]]
Eigen vec_t:
[[  5.55111512e-17  -1.00000000e+00  -1.11022302e-16]
 [  0.00000000e+00   1.00000000e+00   0.00000000e+00]
 [ -9.53462589e-02  -9.53462589e-01   2.86038777e-01]]
Eigenvalue: 1.0000000000000004
Eigenvector: [  5.55111512e-17  -1.00000000e+00  -1.11022302e-16]
Eigenvalue: 1.0
Eigenvector: [ 0.  1.  0.]
Eigenvalue: -2.220446049250313e-16
Eigenvector: [-0.09534626 -0.95346259  0.28603878]


In [7]:
# Calculate eigen vectors and eigenvalues by hand for real

A = np.array([
    [-2, -4, 2],
    [-2, 1, 2],
    [4, 2, 5]
])

In [8]:
np.linalg.eig(A)

(array([-5.,  3.,  6.]), array([[ 0.81649658,  0.53452248,  0.05842062],
        [ 0.40824829, -0.80178373,  0.35052374],
        [-0.40824829, -0.26726124,  0.93472998]]))

In [9]:
# Calculate PCA "by hand"

# 1. Calculate covariance matrix
X = np.array([
    [2.5, 2.4],
    [0.5, 0.7],
    [2.2, 2.9],
    [1.9, 2.2], 
    [3.1, 3.0],
    [2.3, 2.7],
    [2, 1.6],
    [1, 1.1],
    [1.5, 1.6],
    [1.1, 0.9]
])
X_mean = X.mean(axis=0, keepdims=True)
X_scaled = X - X_mean

cov = np.cov(X_scaled.T) 
cov = (X - X_mean).T @ (X - X_mean) / (len(X) - 1)
print(f"cov:\n {cov}")

# 2. Calculate eigenvalues, and eigenvectors
eigen_val, eigen_vec = calc_sorted_eigen(cov)

print(f"eigen_val:\n {eigen_val}")
print(f"eigen_vec:\n {eigen_vec}") 

# 3. Do the transformation
"""
Since the eigenvectors we get back from np.linalg.eig is the transpose of the eigenvectors, 
i.e. the first eigenvector is on the first row, we can multiply the transposed eigenvectors by our original feature
vector, remember that the eigenvectors tell us what proportion of each feature is needed to construct a new axis.

Assuming that the eigenvectors are sorted by their corresponding eigenvalues

eigen_vectors = [
    [V1_x1, V1_x2]
    [V2_x1, V2_x2]
]

Then, the first principle component can be calculated via:

eigen_vectors[0] = [V1_x1, V1_x2]
X[0] = [2.5, 2.4]

2.5 * [V1_x1] + 2.4 * [V1_x2] = eigen_vectors[0] @ X[0]

The second PC can be calculated via:

eigen_vectors[1] = [V2_x1, V2_x2]
X[0] = [2.5, 2.4]

2.5 * [V2_x1] + 2.4 [V2_x2] = eigen_vectors[1] @ X[0]

Or if we want both:

2.5 * [[V1_x1], + 2.4 * [[V1_x2] = eigen_vectors @ X[0]
       [V2_x1]]          [V2_x2]

Note here that 2.5 is the original x1 of the data and 2.4 is the original x2 of the data. By taking the first PC we
can condense these two features into 1, and the proportion of each feature we use is represented by the first eigen 
vector
"""

transformed_X = X @ eigen_vec
print(f"Transformed X:\n {transformed_X}")

# To get the original data back we just have to multiply the transformed data by the eigenvectors again, as the matrix
# created by the eigenvectors is an orthogonal matrix.

original_X = transformed_X @ eigen_vec.T
print(f"Original X:\n {original_X}")

pca.fit(StandardScaler().fit_transform(X))



cov:
 [[ 0.61655556  0.61544444]
 [ 0.61544444  0.71655556]]
eigen_val:
 [ 1.28402771  0.0490834 ]
eigen_vec:
 [[-0.6778734  -0.73517866]
 [-0.73517866  0.6778734 ]]
Transformed X:
 [[-3.45911227 -0.21105048]
 [-0.85356176  0.10692205]
 [-3.62333958  0.34843981]
 [-2.9053525   0.09448203]
 [-4.3069435  -0.24543364]
 [-3.54409119  0.13934727]
 [-2.53203265 -0.38575987]
 [-1.48656992  0.01048208]
 [-2.19309595 -0.01817055]
 [-1.40732153 -0.19861046]]
Original X:
 [[ 2.5  2.4]
 [ 0.5  0.7]
 [ 2.2  2.9]
 [ 1.9  2.2]
 [ 3.1  3. ]
 [ 2.3  2.7]
 [ 2.   1.6]
 [ 1.   1.1]
 [ 1.5  1.6]
 [ 1.1  0.9]]


NameError: name 'pca' is not defined